Add IANA Considerations section.
w3c/cid pull request #129
Opened 2024-11-23 21:30 UTC by msporny

This PR is an attempt to address issue #127 by adding an IANA Considerations section to register the media type for controller documents.

I have marked this PR "DO NOT MERGE" until we have a resolution for the title of the specification.

2024-11-24 00:13 UTC, dlongley approved these changes

2024-11-24 07:19 UTC, iherman approved these changes
I am fine with the content itself,  but the question is whether we should wait until we put a final close on the renaming, or not, of the specification. 

We may want to wait with the merging. Other approach is to merge it but we delay the submission to IANA, with a possible future PR which simply changes the type name itself.

2024-11-25 16:10 UTC, David-Chadwick requested changes
Please do not merge until the name of the document is finalised, because the name registered with IANA may change as well.

2024-12-08 16:45 UTC, msporny commented
This PR has been updated to align with the "Controllable Identifier Document" resolution made earlier this week:

https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-12-04-vcwg#resolution1

2024-12-08 16:58 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-12-08 16:58 UTC, merged